format: yaml
sourceDir: {{ .chezmoi.sourceDir | quote }}

# Global settings
umask: 0o022
color: true
progress: true
verbose: true

# Template settings  
data:
  # Team defaults (can be overridden by user config)
  editor: "helix"
  shell: "fish"
  
  # Tool preferences
  cat_replacement: "bat"
  ls_replacement: "eza"  
  grep_replacement: "ripgrep"
  find_replacement: "fd"
  cd_replacement: "zoxide"

# OS-specific behavior
{{- if eq .chezmoi.os "darwin" }}
  package_manager: "homebrew"
  config_dir: "{{ .chezmoi.homeDir }}/.config"
{{- else if eq .chezmoi.os "linux" }}
  package_manager: "apt"
  config_dir: "{{ .chezmoi.homeDir }}/.config"
{{- end }}

# Architecture detection
arch: {{ .chezmoi.arch | quote }}
hostname: {{ .chezmoi.hostname | quote }}

# Git settings
git:
  autoCommit: false
  autoPush: false

# Merge strategy
merge:
  command: "{{ .editor }}"
  args: ["{{ "{{ .Destination }}" }}", "{{ "{{ .Source }}" }}", "{{ "{{ .Target }}" }}"]

# Age encryption (for secrets)
encryption: "age"
age:
  identity: "{{ .chezmoi.homeDir }}/.config/chezmoi/key.txt"
  recipient: "{{ .chezmoi.homeDir }}/.config/chezmoi/key.txt.pub"

# CD hook to run after chezmoi cd
cd:
  command: "{{ .shell }}"